INSERT INTO rss.role (id, name) VALUES (default, 'admin');
INSERT INTO rss.role (id, name) VALUES (default, 'customer');

INSERT INTO rss."user" (id, role_id, username, password, status) VALUES (default, 1, 'admin', '123', 'A');
INSERT INTO rss."user" (id, role_id, username, password, status) VALUES (default, 2, 'customer', '123', 'A');

INSERT INTO rss.category (id, name) VALUES (default, 'Sport');
INSERT INTO rss.category (id, name) VALUES (default, 'Poliitika');
INSERT INTO rss.category (id, name) VALUES (default, 'Kultuur');
INSERT INTO rss.category (id, name) VALUES (default, 'Krimi');
INSERT INTO rss.category (id, name) VALUES (default, 'Uudised');
INSERT INTO rss.category (id, name) VALUES (default, 'Välismaa');
INSERT INTO rss.category (id, name) VALUES (default, 'Majandus');

INSERT INTO rss.portal (id, name, xml_link, status) VALUES (default, 'ERR', 'https://www.err.ee/rss', 'A');
INSERT INTO rss.portal (id, name, xml_link, status) VALUES (default, 'Delfi', 'https://feeds2.feedburner.com/delfiuudised', 'A');
INSERT INTO rss.portal (id, name, xml_link, status) VALUES (default, 'Postimees', 'https://www.postimees.ee/rss', 'A');
INSERT INTO rss.portal (id, name, xml_link, status) VALUES (default, 'Äripäev', 'https://www.aripaev.ee/rss', 'A');



INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 2, 'Eesti', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 2, 'Podcastid', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 2, 'Maailm', 6);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 2, 'Krimi', 4);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 2, 'Sisuturundus', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 2, 'Uudised', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 2, 'Välismaa', 6);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Eesti uudised', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Välisuudised (Välismaa)', 6);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Majandus', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Teadus', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Kultuur', 3);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Sport', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Eeter (raadio / audio-uudised)', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Ilm', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Arvamus', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Kodu', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 3, 'Kinnisvara', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Raadiouudised', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Teleuudised', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Freestyle-suusatamine', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Ringvaade', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Eesti', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Autoralli', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Välismaa', 6);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Muusika', 3);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Jalgpall', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Korvpall', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Majandus', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Kahevõistlus', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Korvpalli Eesti koondis', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Iluuisutamine', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'ETV spordisaade', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'ilm', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Jalgrattasport', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Teater', 3);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'ETV uudised', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Film', 3);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 1, 'Vormelisport', 1);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Saated', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Arvamused', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Börsiuudised', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Majandustulemused', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Uudised', 5);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Investor Toomas', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Intervjuu', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'TOP', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Suur lugu', 7);
INSERT INTO rss.portal_category (id, portal_id, portal_category_name, category_id) VALUES (default, 4, 'Juhtkiri', 7);
